
services:
  localstack:
    image: localstack/localstack:3
    container_name: sea-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,sns,sqs
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=0
    volumes:
      - "./localstack:/etc/localstack/init/ready.d"
      - "/var/run/docker.sock:/var/run/docker.sock"